# Generated by Django 3.0.5 on 2020-04-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerQueueElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField(default='Run has not been started')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
                ('schedule', models.CharField(choices=[('D', 'Daily'), ('H', 'Hourly'), ('W', 'Weekly')], default='W', max_length=1)),
                ('start_date', models.DateField()),
                ('latitude', models.CharField(blank=True, default='49.000', max_length=20)),
                ('longitude', models.CharField(blank=True, default='9.000', max_length=20)),
                ('street', models.CharField(max_length=200, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code', models.IntegerField(default=-1)),
                ('execution_time', models.DateTimeField()),
                ('schedule_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webfrontent.CrawlerQueueElement')),
            ],
        ),
        migrations.AddField(
            model_name='crawlerqueueelement',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfrontent.Website'),
        ),
        migrations.CreateModel(
            name='WebsiteElementMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dtstart', 'Start Date'), ('tstart', 'Start Time'), ('details', 'Details'), ('tend', 'End Time'), ('link', 'Source Link'), ('summary', 'Summary'), ('dtend', 'End Date')], default='summary', max_length=20)),
                ('html_element', models.CharField(max_length=50)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfrontent.Website')),
            ],
            options={
                'unique_together': {('name', 'website')},
            },
        ),
    ]
