# Generated by Django 3.0.5 on 2020-04-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlerrun',
            name='schedule_element',
        ),
        migrations.AddField(
            model_name='crawlerrun',
            name='crawler_queue_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webfrontent.CrawlerQueueElement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websiteelementmapping',
            name='name',
            field=models.CharField(choices=[('tstart', 'Start Time'), ('link', 'Source Link'), ('dtstart', 'Start Date'), ('tend', 'End Time'), ('details', 'Details'), ('summary', 'Summary'), ('dtend', 'End Date')], default='summary', max_length=20),
        ),
    ]
