# Generated by Django 3.0.5 on 2020-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmapping',
            name='name',
            field=models.CharField(choices=[('details', 'Details'), ('summary', 'Summary'), ('tend', 'End Time'), ('link', 'Source Link'), ('dtend', 'End Date'), ('dtstart', 'Start Date'), ('tstart', 'Start Time')], default='summary', max_length=20),
        ),
    ]
