# Generated by Django 3.0.5 on 2020-04-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfrontent.Website')),
            ],
        ),
    ]
