# Generated by Django 3.0.5 on 2020-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontent', '0002_auto_20200416_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteelementmapping',
            name='name',
            field=models.CharField(choices=[('summary', 'Summary'), ('dtstart', 'Start Date'), ('dtend', 'End Date'), ('link', 'Source Link'), ('details', 'Details'), ('tend', 'End Time'), ('tstart', 'Start Time')], default='summary', max_length=20),
        ),
    ]
