# Generated by Django 3.0.5 on 2020-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfrontent', '0003_auto_20200416_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteelementmapping',
            name='name',
            field=models.CharField(choices=[('tstart', 'Start Time'), ('tend', 'End Time'), ('dtend', 'End Date'), ('summary', 'Summary'), ('dtstart', 'Start Date'), ('link', 'Source Link'), ('details', 'Details')], default='summary', max_length=20),
        ),
    ]
